// Error handling 
### Get all movies (should return 200 OK)
GET http://localhost:3000/movies
Content-Type: application/json


### Get single movie (replace ID with an invalid one, should return 400 or 404)
GET http://localhost:3000/movies/67de08382623bd733debd0e3
Content-Type: application/json

### Create a movie (should return 201 Created)
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Dark Knight",
    "genre": "Action",
    "releaseYear": 2008,
    "duration": 152,
    "description": "Batman sets out to dismantle the remaining criminal organizations that plague Gotham City. The arrival of the Joker creates an unrelenting wave of chaos.",
    "status": "completed",
    "rating": 9
}

### Update a movie (invalid ID, should return 400)
PUT http://localhost:3000/movies/67e3e411625a8abd74c15d57
Content-Type: application/json

{
  "title": "The Dark Knight",
    "genre": "Action",
    "releaseYear": 2008,
    "duration": 152,
    "description": "Batman sets out to dismantle the remaining criminal organizations that plague Gotham City. The arrival of the Joker creates an unrelenting wave of chaos.",
    "status": "completed",
    "rating": 9
}

### Delete a movie (invalid ID, should return 400)
DELETE http://localhost:3000/movies/67e3e411625a8abd74c15d57
Content-Type: application/json


//Error handling for users
### GET all users
GET http://localhost:3000/users


### GET a single user
GET http://localhost:3000/users/67de05b92623bd733debd0dc


### POST - Create a new user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doe",
    "username": "moviebuff99",
    "password": "$2a$10$abc123",
    "email": "moviebuff99@example.com",
    "watchlists": []
}


### POST - Create a user with missing data
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "Jane Doe"
}
# This should return a 400 status with an error indicating the missing fields.


### PUT - Update an existing user
PUT http://localhost:3000/users/67de05b92623bd733debd0dc
Content-Type: application/json

{
    "name": "John Doe",
    "username": "moviebuff99",
    "password": "$2a$10$abc123",
    "email": "moviebuff99@example.com",
    "watchlists": []
}


### PUT - Update a user with an invalid ID
PUT http://localhost:3000/users/67de05b92623bd733debd0dc3
Content-Type: application/json

{
    "name": "Updated Name"
}
# This should return a 400 status with an error indicating the ID is invalid.


### DELETE a user
DELETE http://localhost:3000/users/67de05b92623bd733debd0dc
# Replace {id} with a valid user ID. This will delete the user with the given ID.

### DELETE a user with an invalid ID
DELETE http://localhost:3000/users/67de05b92623bd733debd0dc3
# This should return a 400 status with an error indicating the ID is invalid.


